// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBmlkuppb5bZFVkfIRFjyEOTz15dP6MI',
    appId: '1:375847868902:web:34ae888d88b2b61b76de27',
    messagingSenderId: '375847868902',
    projectId: 'projectfirebase-c3c86',
    authDomain: 'projectfirebase-c3c86.firebaseapp.com',
    storageBucket: 'projectfirebase-c3c86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR_lImQIwdnj0I4VnNfYW128xsGDcI-kA',
    appId: '1:375847868902:android:24f094774a7e14db76de27',
    messagingSenderId: '375847868902',
    projectId: 'projectfirebase-c3c86',
    storageBucket: 'projectfirebase-c3c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1suocUrNgftCVvVRKViNjGirGxh9NfAg',
    appId: '1:375847868902:ios:46677091567279c276de27',
    messagingSenderId: '375847868902',
    projectId: 'projectfirebase-c3c86',
    storageBucket: 'projectfirebase-c3c86.appspot.com',
    iosClientId: '375847868902-1k7ruqqofhl2a6a2qqhjtmm5tsmsgle5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1suocUrNgftCVvVRKViNjGirGxh9NfAg',
    appId: '1:375847868902:ios:46677091567279c276de27',
    messagingSenderId: '375847868902',
    projectId: 'projectfirebase-c3c86',
    storageBucket: 'projectfirebase-c3c86.appspot.com',
    iosClientId: '375847868902-1k7ruqqofhl2a6a2qqhjtmm5tsmsgle5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterproject',
  );
}
